name: Bespoke Carat Deployment

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set deployment path based on branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "Deploying to development environment"
            echo "REMOTE_PATH=/var/www/staging" >> $GITHUB_ENV
            echo "${{ secrets.STAGING_ENV }}" >> .env
          else
            echo "Deploying to main environment"
            echo "REMOTE_PATH=/var/www/bespokecarat" >> $GITHUB_ENV
            echo "${{ secrets.PRODUCTION_ENV }}" >> .env
          fi

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: -avz --delete --exclude="node_modules" --exclude=".next"
          path: ./
          remote_path: ${{ env.REMOTE_PATH }}
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: root
          remote_key: ${{ secrets.VPS_SSH_KEY }}

      - name: Reload Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ${{ env.REMOTE_PATH }}
            npm install
            npm run build
            sudo systemctl reload nginx


